// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalIP():Promise<string>;

export function GetSaveDirectory():Promise<string>;

export function OpenSaveDirectory():Promise<void>;

export function SelectDirectory():Promise<string>;

export function SelectFile():Promise<Array<string>>;

export function SelectSaveDirectory():Promise<string>;

export function SetSaveDirectory(arg1:string):Promise<void>;

export function StartReceiveMode(arg1:number):Promise<string>;

export function StartSendMode(arg1:Array<string>,arg2:number):Promise<string>;

export function StopServer():Promise<void>;
