// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalIP() {
  return window['go']['main']['App']['GetLocalIP']();
}

export function GetSaveDirectory() {
  return window['go']['main']['App']['GetSaveDirectory']();
}

export function OpenSaveDirectory() {
  return window['go']['main']['App']['OpenSaveDirectory']();
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectSaveDirectory() {
  return window['go']['main']['App']['SelectSaveDirectory']();
}

export function SetSaveDirectory(arg1) {
  return window['go']['main']['App']['SetSaveDirectory'](arg1);
}

export function StartReceiveMode(arg1) {
  return window['go']['main']['App']['StartReceiveMode'](arg1);
}

export function StartSendMode(arg1, arg2) {
  return window['go']['main']['App']['StartSendMode'](arg1, arg2);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
